//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_MVC.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienBanNghiemThu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BienBanNghiemThu()
        {
            this.CTBienBanNghiemThus = new HashSet<CTBienBanNghiemThu>();
            this.KTV_BBNT = new HashSet<KTV_BBNT>();
        }
    
        public int ID { get; set; }
        public int IDYC { get; set; }
        public Nullable<long> Ma { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<double> DoanhThu { get; set; }
        public Nullable<double> Diem { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual YeuCauPhucVu YeuCauPhucVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTBienBanNghiemThu> CTBienBanNghiemThus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KTV_BBNT> KTV_BBNT { get; set; }
    }
}
