//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_MVC.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiPhiKhac
    {
        public int ID { get; set; }
        public int IDYCPV { get; set; }
        public string TenChiPhi { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> GiaDauVao { get; set; }
        public Nullable<int> DonGia { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual YeuCauPhucVu YeuCauPhucVu { get; set; }
    }
}
