//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_MVC.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTBBNT_MayLanh
    {
        public int ID { get; set; }
        public int IDCTBBNT { get; set; }
        public int IDMay { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual CTBienBanNghiemThu CTBienBanNghiemThu { get; set; }
        public virtual MayLanh MayLanh { get; set; }
    }
}
