//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_MVC.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPhieuNhapVatTu
    {
        public int ID { get; set; }
        public int IDPhieuNhap { get; set; }
        public int IDVatTu { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public Nullable<int> DonGia { get; set; }
        public string NCC { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual PhieuNhapVatTu PhieuNhapVatTu { get; set; }
        public virtual VatTu VatTu { get; set; }
    }
}
