//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_MVC.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPhieuXuatKho
    {
        public int ID { get; set; }
        public int IDPhieuXuat { get; set; }
        public int IDVatDung { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual PhieuXuatKho PhieuXuatKho { get; set; }
        public virtual KhoVatDung KhoVatDung { get; set; }
    }
}
