//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_MVC.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MayLanh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MayLanh()
        {
            this.CTBBNT_MayLanh = new HashSet<CTBBNT_MayLanh>();
        }
    
        public int ID { get; set; }
        public int IDKhachHang { get; set; }
        public string IDDichVu { get; set; }
        public string Ma { get; set; }
        public string TenMay { get; set; }
        public string Model { get; set; }
        public string CongSuat { get; set; }
        public Nullable<System.DateTime> NgayMua { get; set; }
        public string ViTri { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTBBNT_MayLanh> CTBBNT_MayLanh { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
