//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_MVC.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuXuatKho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuXuatKho()
        {
            this.CTPhieuXuatKhoes = new HashSet<CTPhieuXuatKho>();
        }
    
        public int ID { get; set; }
        public int IDKTV { get; set; }
        public Nullable<System.DateTime> NgayXuat { get; set; }
        public Nullable<System.DateTime> NgayTra { get; set; }
        public Nullable<bool> KiemDuyet { get; set; }
        public Nullable<int> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPhieuXuatKho> CTPhieuXuatKhoes { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
