//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_MVC.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuXuatVatTu_KTV
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuXuatVatTu_KTV()
        {
            this.CTPhieuXuatVatTu_KTV = new HashSet<CTPhieuXuatVatTu_KTV>();
        }
    
        public int ID { get; set; }
        public Nullable<System.DateTime> NgayXuat { get; set; }
        public int IDKTV { get; set; }
        public int IDYeuCauPV { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> KiemDuyet { get; set; }
        public Nullable<int> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPhieuXuatVatTu_KTV> CTPhieuXuatVatTu_KTV { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual YeuCauPhucVu YeuCauPhucVu { get; set; }
    }
}
