//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_MVC.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class VatTu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VatTu()
        {
            this.CTPhieuNhapVatTus = new HashSet<CTPhieuNhapVatTu>();
            this.CTPhieuXuatVatTu_Khach = new HashSet<CTPhieuXuatVatTu_Khach>();
            this.CTPhieuXuatVatTu_KTV = new HashSet<CTPhieuXuatVatTu_KTV>();
        }
    
        public int ID { get; set; }
        public string TenVatTu { get; set; }
        public Nullable<double> SoLuong { get; set; }
        public string DonVi { get; set; }
        public Nullable<int> GiaNhap { get; set; }
        public Nullable<int> GiaBan { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPhieuNhapVatTu> CTPhieuNhapVatTus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPhieuXuatVatTu_Khach> CTPhieuXuatVatTu_Khach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPhieuXuatVatTu_KTV> CTPhieuXuatVatTu_KTV { get; set; }
    }
}
