//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP_MVC.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class YeuCauPhucVu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YeuCauPhucVu()
        {
            this.BienBanNghiemThus = new HashSet<BienBanNghiemThu>();
            this.ChiPhiKhacs = new HashSet<ChiPhiKhac>();
            this.PhieuXuatVatTu_KTV = new HashSet<PhieuXuatVatTu_KTV>();
        }
    
        public int ID { get; set; }
        public int IDKhachHang { get; set; }
        public string DiaChiPhucVu { get; set; }
        public Nullable<int> Loai { get; set; }
        public string YeuCau { get; set; }
        public Nullable<System.DateTime> NgayLap { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayLamTiep { get; set; }
        public Nullable<System.DateTime> NgayDuKienTra { get; set; }
        public Nullable<System.DateTime> NgayHoanThanh { get; set; }
        public string LiDo { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> SoNgay { get; set; }
        public Nullable<int> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BienBanNghiemThu> BienBanNghiemThus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiPhiKhac> ChiPhiKhacs { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhieuXuatVatTu_KTV> PhieuXuatVatTu_KTV { get; set; }
    }
}
